return {
  "glepnir/lspsaga.nvim",
  event = "LspAttach",
  dependencies = {
    "nvim-treesitter/nvim-treesitter",
    "nvim-tree/nvim-web-devicons",
  },
  opts = {
    ui = {
      border = "rounded",
      winblend = 0,
      title = true,
      code_action = "💡",
      diagnostic = "🔍",
      kind = {
        -- For the best experience with icons, use a nerd font
        -- https://www.nerdfonts.com/
        -- You can also customize icons for each LSP kind
        File = { "󰈙", "File" },
        Module = { "󰆧", "Module" },
        Namespace = { "󰅪", "Namespace" },
        Package = { "󰏗", "Package" },
        Class = { "󰠱", "Class" },
        Method = { "󰆧", "Method" },
        Property = { "󰜢", "Property" },
        Field = { "󰜢", "Field" },
        Constructor = { "󰆧", "Constructor" },
        Enum = { "󰕘", "Enum" },
        Interface = { "󰕘", "Interface" },
        Function = { "󰊕", "Function" },
        Variable = { "󰀫", "Variable" },
        Constant = { "󰏿", "Constant" },
        String = { "󰀬", "String" },
        Number = { "󰎠", "Number" },
        Boolean = { "󰨙", "Boolean" },
        Array = { "󰅪", "Array" },
        Object = { "󰅩", "Object" },
        Key = { "󰌋", "Key" },
        Null = { "󰟢", "Null" },
        EnumMember = { "󰊫", "EnumMember" },
        Struct = { "󰙅", "Struct" },
        Event = { "󰉦", "Event" },
        Operator = { "󰆕", "Operator" },
        TypeParameter = { "󰊄", "TypeParameter" },
      },
    },
    symbol_in_winbar = {
      enable = true,
      separator = " › ",
      hide_keyword = true,
      show_file = true,
      folder_level = 2,
      respect_root = false,
      color_mode = true,
    },
    lightbulb = {
      enable = false,
      sign = false,
      virtual_text = false,
    },
    beacon = {
      enable = true,
      frequency = 7,
    },
    hover = {
      max_width = 0.6,
      max_height = 0.6,
      open_link = "gx",
      open_browser = "!chrome",
    },
    definition = {
      width = 0.7,
      height = 0.5,
      keys = {
        edit = "<C-c>o",
        vsplit = "<C-c>v",
        split = "<C-c>s",
        tabe = "<C-c>t",
        quit = "q",
        close = "<Esc>",
      },
    },
    code_action = {
      num_shortcut = true,
      show_server_name = true,
      keys = {
        quit = "q",
        exec = "<CR>",
      },
    },
    diagnostic = {
      show_code_action = true,
      show_source = true,
      jump_num_shortcut = true,
      max_width = 0.7,
      max_height = 0.6,
      text_hl_follow = true,
      border_follow = true,
      extend_relatedInformation = true,
      keys = {
        quit = "q",
        exec = "<CR>",
        toggle_or_jump = "<CR>",
        quit_in_show = "q",
      },
    },
    finder = {
      default = "def+ref+imp",
      layout = "float",
      layout_config = {
        height = 0.5,
        width = 0.8,
      },
      keys = {
        jump_to = "p",
        expand_or_jump = "<CR>",
        vsplit = "v",
        split = "s",
        tabe = "t",
        quit = { "q", "<Esc>" },
      },
    },
    outline = {
      win_width = 30,
      auto_preview = false,
      detail = true,
      auto_close = true,
      close_after_jump = true,
      keys = {
        jump = "<CR>",
        quit = "q",
        toggle_or_jump = "<CR>",
      },
    },
    callhierarchy = {
      layout = "float",
      keys = {
        edit = "e",
        vsplit = "v",
        split = "s",
        tabe = "t",
        jump = "<CR>",
        quit = "q",
        expand_collapse = "u",
      },
    },
    implement = {
      enable = true,
      sign = true,
      virtual_text = false,
    },
    rename = {
      in_select = true,
      auto_save = true,
      keys = {
        quit = "<Esc>",
        exec = "<CR>",
        mark = "x",
        confirm = "<CR>",
        in_select = true,
      },
    },
  },
  config = function(_, opts)
    require("lspsaga").setup(opts)
  end,
}